apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: onlin-shop-updater
  namespace: argocd
spec:
  namespace: argocd

  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: "kustomization"

  applicationRefs:
    - namePattern: "online-shop"
      images:
        - alias: online-shop
          imageName: mrhemantksharma/online-shop
